#!/bin/bash

# Script to help create Xcode project for Quota Guard
# This is a helper - you'll still need to manually add files in Xcode

echo "📦 Quota Guard - Xcode Project Setup"
echo ""
echo "Since Swift Package Manager doesn't work well for macOS GUI apps,"
echo "you need to create an Xcode project manually."
echo ""
echo "Steps:"
echo "1. Open Xcode"
echo "2. File > New > Project"
echo "3. Select 'macOS' > 'App'"
echo "4. Fill in:"
echo "   - Product Name: QuotaGuard"
echo "   - Team: (your development team)"
echo "   - Organization Identifier: com.agenticindiedev"
echo "   - Interface: SwiftUI"
echo "   - Language: Swift"
echo "5. Save to: $(pwd)"
echo ""
echo "6. After creating the project:"
echo "   - Delete the default ContentView.swift and QuotaGuardApp.swift"
echo "   - Add all files from QuotaGuard/ folder to the project"
echo "   - Make sure Info.plist is included"
echo "   - Set LSUIElement to YES in Info.plist"
echo ""
echo "See XCODE_SETUP.md for detailed instructions."
echo ""
echo "Alternatively, you can try opening this directory in Xcode:"
echo "  open -a Xcode ."
echo ""
echo "Xcode might auto-detect the Package.swift and create a scheme,"
echo "but it won't work properly for a GUI app."

